"""initial

Revision ID: 708b603dbc48
Revises: 
Create Date: 2023-12-26 16:36:23.238008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708b603dbc48'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('satellite',
    sa.Column('satelliteId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('expireDate', sa.DateTime(), nullable=True),
    sa.Column('orbitRadius', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('satelliteId')
    )
    op.create_index(op.f('ix_satellite_title'), 'satellite', ['title'], unique=False)
    op.create_table('tvchannel',
    sa.Column('tvChannelId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('broadcastingLanguage', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('telecompany', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('tvChannelId')
    )
    op.create_table('broadcasting',
    sa.Column('broadcasting_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tvChannelId', sa.Integer(), nullable=True),
    sa.Column('satelliteId', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('zoneStart', sa.Integer(), nullable=True),
    sa.Column('zoneEnd', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['satelliteId'], ['satellite.satelliteId'], ),
    sa.ForeignKeyConstraint(['tvChannelId'], ['tvchannel.tvChannelId'], ),
    sa.PrimaryKeyConstraint('broadcasting_id')
    )
    op.create_index(op.f('ix_broadcasting_broadcasting_id'), 'broadcasting', ['broadcasting_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_broadcasting_broadcasting_id'), table_name='broadcasting')
    op.drop_table('broadcasting')
    op.drop_table('tvchannel')
    op.drop_index(op.f('ix_satellite_title'), table_name='satellite')
    op.drop_table('satellite')
    # ### end Alembic commands ###
