"""tvchannelIndex

Revision ID: 860c11a5f1d2
Revises: 708b603dbc48
Create Date: 2023-12-26 16:38:58.782091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '860c11a5f1d2'
down_revision: Union[str, None] = '708b603dbc48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tvchannel_tvChannelId'), 'tvchannel', ['tvChannelId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tvchannel_tvChannelId'), table_name='tvchannel')
    # ### end Alembic commands ###
